import "@/styles/index.scss";

export const metadata = {
	title: "Myteam",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
